name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Check out Git repositor
    - name: Install dependencies
      run: |
       mkdir SampleArtifact
    - name: Check out Git repositor
      uses: actions/checkout@v3
      with:
        node-version : '17.x'
        # Install newman and reporter
    - name: Install newman   
      run: |
       npm install -g newman
       npm install -g newman-reporter-htmlextra
    - name: Seed mongo
      run: mongo 127.0.0.1/infinite-digital-postman-tests  test/postman/setup.js
    - name: Run the API and Postman's tests
      run: | 
       npm run start:dev &
       sleep 60
       newman run "Example.postman_collection.json"
    env:
      MONGO_URI: "mongodb://127.0.0.1:27017/test-db"
      PORT: "3000"
      STAGE: "local"
      NODE_ENV: "develop"  
